security:
    encoders:
        in_memory:
            class: Symfony\Component\Security\Core\User\User
            algorithm:   sha512
            iterations: 1
            encode_as_base64: false


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:

        in_memory:
            memory:
                users:
                    admin: { password: c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        admin_login:
                    pattern:  ^/admin/login$
                    security: false

        admin_secured_area:

            pattern:    ^/admin
            form_login:
                provider: in_memory
                check_path: admin_security_check
                login_path: admin_login
                default_target_path: blog_admin_dashboard

            logout:
                path:   app_admin_logout
                target: admin_login

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER



    access_control:

        admin_login:
            path: ^/admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        admin_secured_area:
            path: ^/admin/*
            roles: ROLE_ADMIN
