<?php

namespace Proxies\__CG__\App\GrabberBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contents extends \App\GrabberBundle\Entity\Contents implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'id', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'subtopic', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'title', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'date', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'post', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'img_url', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'author_name', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'author_avatar_url', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'author_category');
        }

        return array('__isInitialized__', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'id', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'subtopic', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'title', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'date', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'post', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'img_url', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'author_name', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'author_avatar_url', '' . "\0" . 'App\\GrabberBundle\\Entity\\Contents' . "\0" . 'author_category');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contents $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtopic($subtopic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtopic', array($subtopic));

        return parent::setSubtopic($subtopic);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtopic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtopic', array());

        return parent::getSubtopic();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPost($post)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPost', array($post));

        return parent::setPost($post);
    }

    /**
     * {@inheritDoc}
     */
    public function getPost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPost', array());

        return parent::getPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgUrl($imgUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgUrl', array($imgUrl));

        return parent::setImgUrl($imgUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgUrl', array());

        return parent::getImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorName($authorName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorName', array($authorName));

        return parent::setAuthorName($authorName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorName', array());

        return parent::getAuthorName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorAvatarUrl($authorAvatarUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorAvatarUrl', array($authorAvatarUrl));

        return parent::setAuthorAvatarUrl($authorAvatarUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorAvatarUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorAvatarUrl', array());

        return parent::getAuthorAvatarUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorCategory($authorCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorCategory', array($authorCategory));

        return parent::setAuthorCategory($authorCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorCategory', array());

        return parent::getAuthorCategory();
    }

}
